#!/usr/bin/env bash
gcp_project="di-gcp-351221"
gcp_region="asia-south1"
gcp_zone="asia-south1-a"
terraform_gcs_name="devops-terraform-state-01"
jenkins_bkp_gcs="devops-jenkins-bkp"
domain="nttd.dedyn.io"
jenkins_subdomain="jenkins"
app_subdomain="app"

github_base_url="https://github.com/shrikantpangudwale-code/gcp-devops-base.git"